//! Every vanilla block state the client knows, from `data/blocks.json`,
//! generated by `tools/block_data.py` from Dragonfly's 1.26.50 palette (MIT).
//!
//! A block state's network ID is a hash of its name and states, so a state
//! the client does not know is invisible to it: the server would think a
//! block is there while the client shows air, leaving the spot unusable
//! (found live on 2026-09-27, with states from 1.26.30). Every state placed is
//! checked here, and states from older data are upgraded to known ones.

use std::collections::HashMap;
use std::sync::LazyLock;

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use bedrockrs_protocol::block::{BlockState, StateValue};
use bedrockrs_protocol::packets::BlockEntry;
use serde::Deserialize;

const DATA: &str = include_str!("../data/blocks.json");

/// The states of one block and the values each can take; every combination
/// of them is a valid state.
#[derive(Debug)]
struct BlockStates(Vec<(String, Vec<StateValue>)>);

/// Every vanilla block and its states.
#[derive(Debug)]
pub struct Palette {
    blocks: HashMap<String, BlockStates>,
    /// Each slab's double slab, e.g. `minecraft:oak_slab` → `minecraft:oak_double_slab`
    /// (copper ones put `double_` in the middle), and back.
    double_slabs: HashMap<String, String>,
    single_slabs: HashMap<String, String>,
    /// The definitions of the vanilla blocks Mojang defines in JSON.
    data_driven: Vec<BlockEntry>,
}

/// The palette, loaded on first use.
pub fn palette() -> &'static Palette {
    static PALETTE: LazyLock<Palette> =
        LazyLock::new(|| Palette::parse(DATA).expect("data/blocks.json is valid"));
    &PALETTE
}

impl Palette {
    /// Whether the client knows `state`: a known block, with exactly its
    /// states, each set to one of its values.
    pub fn is_valid(&self, state: &BlockState) -> bool {
        let Some(BlockStates(states)) = self.blocks.get(&state.name) else {
            return false;
        };
        state.states.len() == states.len()
            && states.iter().all(|(name, values)| {
                state
                    .states
                    .iter()
                    .any(|(have, value)| have == name && values.contains(value))
            })
    }

    /// `state` made valid, if its block is known: states the block does not
    /// have are dropped, and missing or out-of-range ones get their default
    /// (see [`default_value`]).
    pub fn upgrade(&self, state: &BlockState) -> Option<BlockState> {
        let BlockStates(states) = self.blocks.get(&state.name)?;
        let mut upgraded = BlockState::new(state.name.clone());
        for (name, values) in states {
            let value = state
                .states
                .iter()
                .find(|(have, value)| have == name && values.contains(value))
                .map(|(_, value)| value.clone())
                .unwrap_or_else(|| default_value(values));
            upgraded = upgraded.with(name.clone(), value);
        }
        Some(upgraded)
    }

    /// The double slab two of slab `name` make, if it is a slab.
    pub fn double_slab(&self, name: &str) -> Option<&str> {
        self.double_slabs.get(name).map(String::as_str)
    }

    /// The slab a double slab is made of.
    pub fn single_slab(&self, double: &str) -> Option<&str> {
        self.single_slabs.get(double).map(String::as_str)
    }

    /// The values state `name` of `block` can take.
    pub fn values(&self, block: &str, name: &str) -> Option<&[StateValue]> {
        let BlockStates(states) = self.blocks.get(block)?;
        states
            .iter()
            .find(|(state, _)| state == name)
            .map(|(_, values)| values.as_slice())
    }

    /// The name of every block.
    pub fn names(&self) -> impl Iterator<Item = &str> {
        self.blocks.keys().map(String::as_str)
    }

    /// Every valid state of every block.
    pub fn all_states(&self) -> impl Iterator<Item = BlockState> + '_ {
        self.blocks.iter().flat_map(|(name, BlockStates(states))| {
            let mut combinations = vec![BlockState::new(name.clone())];
            for (state, values) in states {
                combinations = combinations
                    .into_iter()
                    .flat_map(|partial| {
                        values
                            .iter()
                            .map(move |value| partial.clone().with(state.clone(), value.clone()))
                    })
                    .collect();
            }
            combinations
        })
    }

    /// The vanilla blocks Mojang defines in JSON (wool slabs and the like),
    /// for StartGame: without their definitions the client does not know them.
    pub fn data_driven(&self) -> &[BlockEntry] {
        &self.data_driven
    }

    pub fn len(&self) -> usize {
        self.blocks.len()
    }

    pub fn is_empty(&self) -> bool {
        self.blocks.is_empty()
    }

    fn parse(json: &str) -> Result<Self, String> {
        #[derive(Deserialize)]
        struct Raw {
            blocks: HashMap<String, Vec<(String, String, Vec<serde_json::Value>)>>,
            data_driven: Vec<RawDefinition>,
        }
        #[derive(Deserialize)]
        struct RawDefinition {
            name: String,
            /// Network NBT, base64.
            properties: String,
        }
        let raw: Raw = serde_json::from_str(json).map_err(|err| err.to_string())?;
        let mut blocks = HashMap::with_capacity(raw.blocks.len());
        for (name, states) in raw.blocks {
            let states = states
                .into_iter()
                .map(|(state, kind, values)| {
                    let values = values
                        .iter()
                        .map(|value| parse_value(&kind, value))
                        .collect::<Option<Vec<_>>>()
                        .ok_or_else(|| format!("bad values for {state} of {name}"))?;
                    Ok((state, values))
                })
                .collect::<Result<_, String>>()?;
            blocks.insert(name, BlockStates(states));
        }
        let mut double_slabs = HashMap::new();
        let mut single_slabs = HashMap::new();
        for double in blocks
            .keys()
            .filter(|name| name.contains("double") && name.ends_with("_slab"))
        {
            let single = double
                .replace("double_", "")
                .replace("_double_slab", "_slab");
            if blocks.contains_key(&single) {
                double_slabs.insert(single.clone(), double.clone());
                single_slabs.insert(double.clone(), single);
            }
        }
        let data_driven = raw
            .data_driven
            .into_iter()
            .map(|definition| {
                let properties = STANDARD
                    .decode(&definition.properties)
                    .map_err(|err| format!("bad definition of {}: {err}", definition.name))?;
                Ok(BlockEntry {
                    name: definition.name,
                    properties,
                })
            })
            .collect::<Result<_, String>>()?;
        Ok(Self {
            blocks,
            double_slabs,
            single_slabs,
            data_driven,
        })
    }
}

/// The value a state gets when nothing says otherwise: `none` or `unknown`
/// where a state has one (stairs corners, torch attachment), otherwise the
/// smallest (0 for bits and numbers).
pub fn default_value(values: &[StateValue]) -> StateValue {
    for preferred in ["none", "unknown"] {
        let text = StateValue::String(preferred.to_owned());
        if values.contains(&text) {
            return text;
        }
    }
    values.first().cloned().unwrap_or(StateValue::Byte(0))
}

fn parse_value(kind: &str, value: &serde_json::Value) -> Option<StateValue> {
    match kind {
        "byte" => value
            .as_u64()
            .and_then(|n| u8::try_from(n).ok())
            .map(StateValue::Byte),
        "int" => value
            .as_i64()
            .and_then(|n| i32::try_from(n).ok())
            .map(StateValue::Int),
        "string" => value.as_str().map(|s| StateValue::String(s.to_owned())),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn string(value: &str) -> StateValue {
        StateValue::String(value.into())
    }

    #[test]
    fn the_palette_knows_current_states() {
        let palette = palette();
        assert!(palette.len() > 1400);
        assert_eq!(palette.all_states().count(), 22_091);
        assert!(palette.is_valid(&BlockState::new("minecraft:stone")));
        assert!(
            !palette.is_valid(&BlockState::new("minecraft:iron_bars")),
            "missing its connections"
        );
        assert!(!palette.is_valid(&BlockState::new("minecraft:no_such_block")));
        let bars = BlockState::new("minecraft:iron_bars")
            .with("minecraft:connection_east", StateValue::Byte(1))
            .with("minecraft:connection_north", StateValue::Byte(0))
            .with("minecraft:connection_south", StateValue::Byte(0))
            .with("minecraft:connection_west", StateValue::Byte(1));
        assert!(palette.is_valid(&bars));
    }

    #[test]
    fn json_defined_blocks_come_with_their_definitions() {
        let palette = palette();
        let wool_slab = palette
            .data_driven()
            .iter()
            .find(|block| block.name == "minecraft:white_wool_slab")
            .expect("wool slabs are defined in JSON");
        // A nameless root compound in network NBT.
        assert_eq!(wool_slab.properties[..2], [10, 0]);
        assert!(
            palette
                .data_driven()
                .iter()
                .all(|block| palette.blocks.contains_key(&block.name)),
            "every definition is of a block in the palette"
        );
        assert_eq!(
            palette.double_slab("minecraft:white_wool_slab"),
            Some("minecraft:white_wool_double_slab")
        );
    }

    #[test]
    fn every_slab_has_its_double() {
        let palette = palette();
        assert_eq!(
            palette.double_slab("minecraft:oak_slab"),
            Some("minecraft:oak_double_slab")
        );
        assert_eq!(
            palette.double_slab("minecraft:waxed_cut_copper_slab"),
            Some("minecraft:waxed_double_cut_copper_slab")
        );
        assert_eq!(
            palette.single_slab("minecraft:oak_double_slab"),
            Some("minecraft:oak_slab")
        );
        assert_eq!(palette.double_slab("minecraft:stone"), None);
        assert_eq!(palette.double_slabs.len(), 101);
    }

    #[test]
    fn old_states_are_upgraded() {
        let palette = palette();
        // 1.26.30 stairs had no corner; bars had no connections.
        let old_stairs = BlockState::new("minecraft:oak_stairs")
            .with("upside_down_bit", StateValue::Byte(1))
            .with("weirdo_direction", StateValue::Int(2));
        let stairs = palette.upgrade(&old_stairs).unwrap();
        assert!(palette.is_valid(&stairs));
        assert!(
            stairs
                .states
                .contains(&("minecraft:corner".into(), string("none")))
        );
        assert!(
            stairs
                .states
                .contains(&("weirdo_direction".into(), StateValue::Int(2))),
            "kept"
        );
        let bars = palette
            .upgrade(&BlockState::new("minecraft:iron_bars"))
            .unwrap();
        assert!(palette.is_valid(&bars));
        // A state the block no longer has is dropped.
        let odd = BlockState::new("minecraft:stone").with("stone_type", string("granite"));
        assert_eq!(
            palette.upgrade(&odd),
            Some(BlockState::new("minecraft:stone"))
        );
        assert_eq!(
            palette.upgrade(&BlockState::new("minecraft:no_such_block")),
            None
        );
        // Torches default to no attachment.
        let torch = palette
            .upgrade(&BlockState::new("minecraft:torch"))
            .unwrap();
        assert_eq!(
            torch.states,
            [("torch_facing_direction".into(), string("unknown"))]
        );
    }
}
