//! Every vanilla item, and the creative inventory.
//!
//! The data comes from `data/items.json`, generated by `tools/item_data.py`
//! from Dragonfly's vanilla data. It must match the client's version: the
//! client places creative items by its own network IDs, whatever the
//! ItemRegistry packet says, so older data puts items in the wrong groups.

use std::collections::{HashMap, HashSet};
use std::sync::{LazyLock, Mutex, PoisonError};

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use bedrockrs_protocol::block::{BlockState, StateValue};
use bedrockrs_protocol::packets::{
    CreativeContent, CreativeGroup, CreativeItem, CreativeItemStack, ItemEntry, ItemRegistry,
};
use serde::Deserialize;

use crate::blocks::palette;

const DATA: &str = include_str!("../data/items.json");

/// An item the server knows.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ItemType {
    pub name: String,
    pub network_id: i16,
    version: i32,
    component_based: bool,
    /// Components as encoded network NBT, for component-based items.
    components: Option<Vec<u8>>,
    /// The most a stack of it holds.
    pub max_stack: u8,
    /// For block items, the block state it places.
    pub block: Option<BlockState>,
    /// That block state's network ID.
    pub block_network_id: Option<u32>,
}

/// An item of the creative inventory.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CreativeEntry {
    pub network_id: i16,
    pub metadata: u32,
    /// Its NBT (an enchanted book's enchantment, a firework's flight), as
    /// [`ItemNbt`].
    pub nbt: ItemNbt,
}

/// An item's NBT, as a little-endian compound with its root tag, the form
/// item user data carries; `None` for most items. Each distinct value is
/// kept once for the life of the server (see [`intern_nbt`]), so items stay
/// cheap to copy and compare.
pub type ItemNbt = Option<&'static [u8]>;

/// The one copy of `nbt` kept for the life of the server. There are only as
/// many distinct values as the creative inventory offers, as long as items
/// gain NBT nowhere else.
pub fn intern_nbt(nbt: &[u8]) -> &'static [u8] {
    static INTERNED: LazyLock<Mutex<HashSet<&'static [u8]>>> = LazyLock::new(Default::default);
    let mut interned = INTERNED.lock().unwrap_or_else(PoisonError::into_inner);
    if let Some(&kept) = interned.get(nbt) {
        return kept;
    }
    let kept: &'static [u8] = Box::leak(nbt.into());
    interned.insert(kept);
    kept
}

/// The item registry: every item by network ID and by name, and the
/// creative inventory.
#[derive(Debug)]
pub struct Items {
    types: Vec<ItemType>,
    by_id: HashMap<i16, usize>,
    by_name: HashMap<String, usize>,
    creative_groups: Vec<CreativeGroup>,
    /// Creative items; creative network ID `n` is entry `n - 1`.
    creative: Vec<(CreativeEntry, u32)>,
    /// The items the creative inventory offers, by network ID.
    in_creative: HashSet<i16>,
}

/// The registry, loaded on first use.
pub fn items() -> &'static Items {
    static ITEMS: LazyLock<Items> =
        LazyLock::new(|| Items::parse(DATA).expect("data/items.json is valid"));
    &ITEMS
}

impl Items {
    pub fn get(&self, network_id: i16) -> Option<&ItemType> {
        self.by_id.get(&network_id).map(|&index| &self.types[index])
    }

    pub fn by_name(&self, name: &str) -> Option<&ItemType> {
        self.by_name.get(name).map(|&index| &self.types[index])
    }

    pub fn len(&self) -> usize {
        self.types.len()
    }

    pub fn is_empty(&self) -> bool {
        self.types.is_empty()
    }

    /// The creative item with creative network ID `id`.
    pub fn creative(&self, id: u32) -> Option<CreativeEntry> {
        let index = usize::try_from(id.checked_sub(1)?).ok()?;
        self.creative.get(index).map(|(entry, _)| *entry)
    }

    /// The item picking `block` (a block name) gives, as vanilla's pick block
    /// does: the obtainable item that places it, or `None` for blocks with
    /// none (air, liquids, fire, portals).
    pub fn pick(&self, block: &str) -> Option<&ItemType> {
        let name = block.strip_prefix("minecraft:")?;
        if NOT_PICKABLE.contains(&name) {
            return None;
        }
        let item = |name: &str| self.by_name(&format!("minecraft:{name}"));
        let obtainable =
            |name: &str| item(name).filter(|item| self.in_creative.contains(&item.network_id));
        if let Some(&(_, picked)) = PICKED_AS.iter().find(|(block, _)| *block == name) {
            return item(picked);
        }
        if name.ends_with("_candle_cake") {
            return item("cake");
        }
        if let Some(single) = palette().single_slab(block) {
            return self.by_name(single);
        }
        if let Some(found) = obtainable(name) {
            return Some(found);
        }
        // The forms a block takes while lit, powered or on a wall.
        let mut forms = Vec::new();
        for prefix in ["lit_", "unlit_", "powered_", "unpowered_"] {
            forms.extend(name.strip_prefix(prefix).map(str::to_owned));
        }
        forms.extend(name.strip_suffix("_inverted").map(str::to_owned));
        for suffix in ["_wall_sign", "_standing_sign"] {
            forms.extend(name.strip_suffix(suffix).map(|wood| format!("{wood}_sign")));
        }
        forms.extend(
            name.strip_suffix("_wall_fan")
                .map(|coral| format!("{coral}_fan")),
        );
        if let Some(found) = forms.iter().find_map(|form| obtainable(form)) {
            return Some(found);
        }
        // Blocks only operators get (barriers, command and light blocks)
        // still give their own item.
        item(name)
    }

    /// Every block state an item places.
    pub fn block_states(&self) -> impl Iterator<Item = &BlockState> {
        self.types.iter().filter_map(|item| item.block.as_ref())
    }

    /// The ItemRegistry packet: every item, sent with StartGame.
    pub fn registry_packet(&self) -> ItemRegistry {
        ItemRegistry {
            items: self
                .types
                .iter()
                .map(|item| ItemEntry {
                    name: item.name.clone(),
                    runtime_id: item.network_id,
                    component_based: item.component_based,
                    version: item.version,
                    components: item.components.clone(),
                })
                .collect(),
        }
    }

    /// The CreativeContent packet: the creative inventory's groups and items.
    pub fn creative_packet(&self) -> CreativeContent {
        CreativeContent {
            groups: self.creative_groups.clone(),
            items: self
                .creative
                .iter()
                .zip(1..)
                .map(|((entry, group), network_id)| CreativeItem {
                    network_id,
                    item: self.creative_stack(entry.network_id, entry.metadata, entry.nbt),
                    group: *group,
                })
                .collect(),
        }
    }

    /// One of an item as the creative inventory shows it.
    fn creative_stack(&self, network_id: i16, metadata: u32, nbt: ItemNbt) -> CreativeItemStack {
        let item = self.get(network_id);
        CreativeItemStack {
            network_id,
            count: 1,
            metadata,
            block_runtime_id: item.and_then(|item| item.block_network_id).unwrap_or(0),
            shield: item.is_some_and(|item| item.name == SHIELD),
            nbt,
        }
    }

    fn parse(json: &str) -> Result<Self, String> {
        let data: RawData = serde_json::from_str(json).map_err(|err| err.to_string())?;
        let mut items = Self {
            types: Vec::with_capacity(data.items.len()),
            by_id: HashMap::new(),
            by_name: HashMap::new(),
            creative_groups: Vec::new(),
            creative: Vec::new(),
            in_creative: HashSet::new(),
        };
        for raw in data.items {
            let block = raw.block.map(RawBlock::state).transpose()?;
            let components = raw
                .components
                .map(|encoded| STANDARD.decode(encoded).map_err(|err| err.to_string()))
                .transpose()?;
            let index = items.types.len();
            items.by_id.insert(raw.id, index);
            items.by_name.insert(raw.name.clone(), index);
            items.types.push(ItemType {
                block_network_id: block.as_ref().map(BlockState::network_id),
                name: raw.name,
                network_id: raw.id,
                version: raw.version,
                component_based: raw.component_based,
                components,
                max_stack: raw.max_stack.max(1),
                block,
            });
        }

        let id_of = |name: &str| {
            items
                .by_name(name)
                .map(|item| item.network_id)
                .ok_or_else(|| format!("unknown item {name}"))
        };
        let mut groups = Vec::with_capacity(data.creative_groups.len());
        for group in data.creative_groups {
            let icon = match group.icon {
                Some(icon) => items.creative_stack(id_of(&icon.item)?, 0, None),
                None => CreativeItemStack::default(),
            };
            groups.push(CreativeGroup {
                category: group.category,
                name: group.name,
                icon,
            });
        }
        let mut creative = Vec::with_capacity(data.creative_items.len());
        for entry in data.creative_items {
            let network_id = id_of(&entry.item)?;
            let nbt = entry
                .nbt
                .map(|encoded| STANDARD.decode(encoded).map_err(|err| err.to_string()))
                .transpose()?
                .map(|nbt| intern_nbt(&nbt));
            creative.push((
                CreativeEntry {
                    network_id,
                    metadata: entry.meta,
                    nbt,
                },
                entry.group,
            ));
        }
        items.creative_groups = groups;
        items.in_creative = creative.iter().map(|(entry, _)| entry.network_id).collect();
        items.creative = creative;
        Ok(items)
    }
}

/// The armour slot an item is worn in (0 head, 1 chest, 2 legs, 3 feet), or
/// `None` if it is not worn. Heads include skulls and the carved pumpkin.
pub fn armor_slot(name: &str) -> Option<usize> {
    let name = name.strip_prefix("minecraft:")?;
    if name.ends_with("_helmet")
        || name.ends_with("_skull")
        || name.ends_with("_head")
        || name == "carved_pumpkin"
    {
        Some(0)
    } else if name.ends_with("_chestplate") || name == "elytra" {
        Some(1)
    } else if name.ends_with("_leggings") {
        Some(2)
    } else if name.ends_with("_boots") {
        Some(3)
    } else {
        None
    }
}

/// The sound of putting `name` on, as a sound event: by the armour's
/// material, as Dragonfly picks it.
pub fn equip_sound(name: &str) -> &'static str {
    let name = name.strip_prefix("minecraft:").unwrap_or(name);
    let materials = [
        ("leather_", "armor.equip_leather"),
        ("chainmail_", "armor.equip_chain"),
        ("iron_", "armor.equip_iron"),
        ("golden_", "armor.equip_gold"),
        ("diamond_", "armor.equip_diamond"),
        ("netherite_", "armor.equip_netherite"),
        ("copper_", "armor.equip_copper"),
    ];
    if name == "elytra" {
        return "armor.equip_elytra";
    }
    materials
        .iter()
        .find(|(prefix, _)| name.starts_with(prefix))
        .map_or("armor.equip_generic", |(_, sound)| sound)
}

/// Blocks picking gives nothing for, as in vanilla.
const NOT_PICKABLE: &[&str] = &[
    "air",
    "water",
    "flowing_water",
    "lava",
    "flowing_lava",
    "fire",
    "soul_fire",
    "portal",
    "end_portal",
    "end_gateway",
    "bubble_column",
    "frosted_ice",
    "moving_block",
    "piston_arm_collision",
    "sticky_piston_arm_collision",
    "client_request_placeholder_block",
    "unknown",
];

/// Blocks whose item has another name: crops give their seeds, wires what
/// they are made of.
const PICKED_AS: &[(&str, &str)] = &[
    ("wheat", "wheat_seeds"),
    ("beetroot", "beetroot_seeds"),
    ("carrots", "carrot"),
    ("potatoes", "potato"),
    ("melon_stem", "melon_seeds"),
    ("pumpkin_stem", "pumpkin_seeds"),
    ("torchflower_crop", "torchflower_seeds"),
    ("pitcher_crop", "pitcher_pod"),
    ("cocoa", "cocoa_beans"),
    ("sweet_berry_bush", "sweet_berries"),
    ("cave_vines", "glow_berries"),
    ("cave_vines_body_with_berries", "glow_berries"),
    ("cave_vines_head_with_berries", "glow_berries"),
    ("bamboo_sapling", "bamboo"),
    ("reeds", "sugar_cane"),
    ("redstone_wire", "redstone"),
    ("trip_wire", "string"),
    ("powder_snow", "powder_snow_bucket"),
    ("candle_cake", "cake"),
    ("standing_sign", "oak_sign"),
    ("wall_sign", "oak_sign"),
    ("darkoak_standing_sign", "dark_oak_sign"),
    ("darkoak_wall_sign", "dark_oak_sign"),
    ("standing_banner", "banner"),
    ("wall_banner", "banner"),
    ("stonecutter", "stonecutter_block"),
];

/// The shield, whose item data carries an extra field on the wire.
pub const SHIELD: &str = "minecraft:shield";

#[derive(Deserialize)]
struct RawData {
    items: Vec<RawItem>,
    creative_groups: Vec<RawGroup>,
    creative_items: Vec<RawCreativeItem>,
}

#[derive(Deserialize)]
struct RawItem {
    name: String,
    id: i16,
    version: i32,
    component_based: bool,
    components: Option<String>,
    max_stack: u8,
    block: Option<RawBlock>,
}

#[derive(Deserialize)]
struct RawBlock {
    name: String,
    /// `[name, type, value]`, type being `byte`, `int` or `string`.
    states: Vec<(String, String, serde_json::Value)>,
}

impl RawBlock {
    fn state(self) -> Result<BlockState, String> {
        let mut state = BlockState::new(self.name);
        for (name, kind, value) in self.states {
            let value = match (kind.as_str(), &value) {
                ("byte", serde_json::Value::Number(n)) => n
                    .as_i64()
                    .and_then(|n| u8::try_from(n).ok())
                    .map(StateValue::Byte),
                ("int", serde_json::Value::Number(n)) => n
                    .as_i64()
                    .and_then(|n| i32::try_from(n).ok())
                    .map(StateValue::Int),
                ("string", serde_json::Value::String(s)) => Some(StateValue::String(s.clone())),
                _ => None,
            }
            .ok_or_else(|| format!("bad state {name} of {}: {kind} {value}", state.name))?;
            state = state.with(name, value);
        }
        Ok(state)
    }
}

#[derive(Deserialize)]
struct RawGroup {
    category: u8,
    name: String,
    icon: Option<RawIcon>,
}

#[derive(Deserialize)]
struct RawIcon {
    item: String,
}

#[derive(Deserialize)]
struct RawCreativeItem {
    item: String,
    meta: u32,
    group: u32,
    /// Little-endian NBT, base64.
    nbt: Option<String>,
}

#[cfg(test)]
mod tests {
    use bedrockrs_protocol::packet::Encode as _;

    use super::*;

    #[test]
    fn the_registry_holds_vanilla_items_with_vanilla_ids() {
        let items = items();
        assert!(items.len() > 1500, "{}", items.len());
        let stone = items.by_name("minecraft:stone").unwrap();
        assert_eq!(stone.network_id, 1);
        assert_eq!(
            stone.block_network_id,
            Some(BlockState::new("minecraft:stone").network_id())
        );
        let sword = items.by_name("minecraft:diamond_sword").unwrap();
        assert_eq!(sword.max_stack, 1);
        assert_eq!(sword.block, None);
        assert_eq!(items.get(sword.network_id).unwrap().name, sword.name);
        assert_eq!(
            items.by_name("minecraft:ender_pearl").unwrap().max_stack,
            16
        );
        // A block with states places its creative state.
        let log = items.by_name("minecraft:oak_log").unwrap();
        assert_eq!(
            log.block,
            Some(
                BlockState::new("minecraft:oak_log")
                    .with("pillar_axis", StateValue::String("y".into()))
            )
        );
    }

    #[test]
    fn armour_has_a_slot_and_a_sound() {
        assert_eq!(armor_slot("minecraft:turtle_helmet"), Some(0));
        assert_eq!(armor_slot("minecraft:carved_pumpkin"), Some(0));
        assert_eq!(armor_slot("minecraft:creeper_head"), Some(0));
        assert_eq!(armor_slot("minecraft:elytra"), Some(1));
        assert_eq!(armor_slot("minecraft:copper_leggings"), Some(2));
        assert_eq!(armor_slot("minecraft:netherite_boots"), Some(3));
        assert_eq!(armor_slot("minecraft:pumpkin"), None);
        assert_eq!(armor_slot("minecraft:diamond_sword"), None);
        assert_eq!(equip_sound("minecraft:golden_helmet"), "armor.equip_gold");
        assert_eq!(
            equip_sound("minecraft:chainmail_boots"),
            "armor.equip_chain"
        );
        assert_eq!(equip_sound("minecraft:elytra"), "armor.equip_elytra");
        assert_eq!(
            equip_sound("minecraft:turtle_helmet"),
            "armor.equip_generic"
        );
    }

    #[test]
    fn every_block_can_be_picked_but_air_liquids_and_the_like() {
        let items = items();
        let picked = |block: &str| items.pick(block).map(|item| item.name.as_str());
        for block in palette().names() {
            let name = block.strip_prefix("minecraft:").unwrap();
            assert_eq!(
                picked(block).is_none(),
                NOT_PICKABLE.contains(&name),
                "{block} picks {:?}",
                picked(block)
            );
        }
        for (block, item) in [
            ("stone", "stone"),
            ("oak_double_slab", "oak_slab"),
            ("white_wool_double_slab", "white_wool_slab"),
            ("wheat", "wheat_seeds"),
            ("carrots", "carrot"),
            ("lit_furnace", "furnace"),
            ("lit_pumpkin", "lit_pumpkin"),
            ("powered_repeater", "repeater"),
            ("unlit_redstone_torch", "redstone_torch"),
            ("daylight_detector_inverted", "daylight_detector"),
            ("spruce_wall_sign", "spruce_sign"),
            ("wall_sign", "oak_sign"),
            ("darkoak_standing_sign", "dark_oak_sign"),
            ("tube_coral_wall_fan", "tube_coral_fan"),
            ("red_candle_cake", "cake"),
            ("redstone_wire", "redstone"),
            ("barrier", "barrier"),
            ("acacia_door", "acacia_door"),
        ] {
            assert_eq!(
                picked(&format!("minecraft:{block}")),
                Some(format!("minecraft:{item}").as_str()),
                "{block}"
            );
        }
        assert_eq!(picked("minecraft:water"), None);
    }

    #[test]
    fn component_based_items_carry_their_components() {
        let apple = items().by_name("minecraft:apple").unwrap();
        assert!(apple.component_based);
        let components = apple.components.as_ref().unwrap();
        // A nameless root compound in network NBT.
        assert_eq!(components[..2], [10, 0]);
    }

    #[test]
    fn creative_items_are_numbered_from_one() {
        let items = items();
        assert_eq!(items.creative(0), None);
        let first = items.creative(1).unwrap();
        assert_eq!(
            items.get(first.network_id).unwrap().name,
            "minecraft:oak_planks"
        );
        let packet = items.creative_packet();
        assert!(packet.items.len() > 1500);
        assert!(
            packet
                .items
                .iter()
                .all(|item| (item.group as usize) < packet.groups.len())
        );
        assert_eq!(items.creative(packet.items.len() as u32 + 1), None);
        // Both packets encode.
        assert!(packet.encode().len() > 10_000);
        assert!(items.registry_packet().encode().len() > 10_000);
    }
}
